---
- name: Decide if server is supplier or consumer
  ansible.builtin.set_fact:
    dirsrv_instance_is_consumer: "{{ dirsrv_replica_role == 'consumer' or dirsrv_replica_role == 'both' }}"
    dirsrv_instance_is_supplier: "{{ dirsrv_replica_role == 'supplier' or dirsrv_replica_role == 'both' }}"
  tags:
    - changelog

- name: Check that replica role is correctly configured
  ansible.builtin.assert:
    that:
      - dirsrv_instance_is_consumer or dirsrv_instance_is_supplier
    msg: "This server is neither a consumer nor a supplier. Check that \"dirsrv_replica_role\" is set correctly."

# There are 3 possible configurations:
# Supplier ONLY: ✔ changelog, ✔ supplier config, ✘ consumer config, ✔ replication agreement, ✘ replication user.
# Consumer ONLY: ✘ changelog, ✘ supplier config, ✔ consumer config, ✘ replication agreement, ✔ replication user.
# Both (master): ✔ changelog, ✔ supplier config, ✘ consumer config, ✔ replication agreement, ✔ replication user.
# And there's a fourth one, hub, not supported by this role.

- name: Supplier or master/both
  ansible.builtin.include_tasks: configure_changelog.yml
  when: dirsrv_instance_is_supplier

- name: Consumer or master/both
  ansible.builtin.include_tasks: configure_replication_user.yml
  when: dirsrv_instance_is_consumer

- name: Consumer
  ansible.builtin.include_tasks: configure_consumer.yml
  when: dirsrv_instance_is_consumer and not dirsrv_instance_is_supplier

- name: Supplier or master/both
  ansible.builtin.include_tasks: configure_supplier.yml
  when: dirsrv_instance_is_supplier

- name: Supplier or master/both
  ansible.builtin.include_tasks: configure_replication_agreement.yml
  when: dirsrv_instance_is_supplier
